### ISSUE TITLE
upload to maven

### ISSUE THREAD

**Issue by yoavst** [ragunathjawahar/android-kotlin-extensions#1]
is it possible?

**Comment by ragunathjawahar** [comment]
Definitely. To start with, I'll push the snapshots to the MC snapshot repository.

**Comment by yoavst** [comment]
Other option is to create release to github and then use [jitpack](https://jitpack.io/).

**Comment by ragunathjawahar** [comment]
`jitpack` is super awesome, however I have a sonatype account already. I'll use that.

**Comment by yoavst** [comment]
before uploading ,see #2 
Also, [KotlinAndroidLib](https://github.com/vladlichonos/kotlinAndroidLib) contains a lot of good methods too, so merging it will be great.

**Comment by ragunathjawahar** [comment]
@yoavst That's interesting, thanks for pointing out. I'll look into both.
